name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  
  # Networking & Files
  http: ^1.6.0
  file_picker: ^10.3.7
  
  # Fonts (Fixes the Noto Font warning)
  google_fonts: ^8.0.0
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true